
public function <?= $this->function_name ?>($dbh<?
foreach ($this->variables as $one) {
    echo ', $' . $one;
}
?>){
<?=$this->custom_header_code;?>

try {

$deleteClause="DELETE FROM  ";
<?
foreach ($this->frome_tables as $one) {
    echo '$deleteClause.="';

    echo '{' . $one['table_variable'] . '}';

    if (!empty($one['table_alias'])) {
        echo " as {$one['table_alias']}";
    }



    echo "\";\n";

    //update only support ont table;
    break;
}
?>
$bind_arr = array();

<?

if (!empty($this->where_claus)) {
    echo '$deleteClause.=" ' . "WHERE {$this->where_claus}\";\n";
}
?>



<?
foreach ($this->variables as $one) {
    echo '$bind_arr[\':' . $one . '\']=$' . $one . ";\n";
}
?>




$stmt = $dbh->prepare($deleteClause);

$stmt_r = $stmt->execute($bind_arr);
if($stmt_r){
return $stmt->rowCount();
}
else {

//echo 'error info:'.  var_export($stmt->errorInfo(),true);
return false;
}


}
catch ( PDOException $x ) {
//$errorMessage="database error: " . $x->getMessage();
throw $x;
}
<?=$this->custom_tailer_code;?>

}
