
$engine='<?= $this->engine ?>';
$host='<?= $this->host ?>';
$port='<?= $this->port ?>';
$user='<?= $this->user ?>';
$dbname='<?if(!empty($this->dbname)):?><?=$this->dbname?><?endif?>';
$password='<?= $this->password ?>';




$dsn = "{$engine}:host={$host};port={$port};dbname={$dbname}";


$initPDO=array();
//$dsn.=';charset=UTF8';

//$initPDO[PDO::MYSQL_ATTR_INIT_COMMAND] = "SET NAMES utf8";

$dbh= new PDO($dsn, $user, $password,$initPDO);
