<? $used_variables = array(); ?>
public function <?= $this->function_name ?>($dbh<?
foreach ($this->variables as $one) {
    echo ', $' . $one;
}
?>){
<?=$this->custom_header_code;?>

try {

$updateClause="UPDATE  ";
<?
foreach ($this->frome_tables as $one) {
    echo '$updateClause.="';

    echo '{' . $one['table_variable'] . '}';

    if (!empty($one['table_alias'])) {
        echo " as {$one['table_alias']}";
    }



    echo "\";\n";

    //update only support ont table;
    break;
}
?>
$bind_arr = array();

$setClumns = " SET ";
<?
$first = true;
foreach ($this->columns as $one) {
    if (!$first) {
        echo '$' . "setClumns .=',`{$one['column_name']}`=';";
    } else {
        echo '$' . "setClumns .=' `{$one['column_name']}`=';";
    }
    $first = false;


    echo "";


    if ($one['type'] === 'variable') {
        echo '$' . "setClumns .=':{$one['value']}';\n";
    } else if ($one['type'] === 'pure') {
        echo '$' . "setClumns .=':fix_{$one['column_name']}';\n";
        echo '$' . "bind_arr[':fix_{$one['column_name']}']='" . str_replace("'", "\\" . "'", $one['value']) . "';\n";
    } else if ($one['type'] === 'function') {
        echo '$' . "setClumns .='{$one['value']}';\n";
    }




    echo "\n";
}

echo '$updateClause.=$setClumns;';

if (!empty($this->where_claus)) {
    echo '$updateClause.=" ' . "WHERE {$this->where_claus}\";\n";
}
?>





<?
foreach ($this->variables as $one) {
    if (empty($used_variables[$one])) {
        echo '$bind_arr[\':' . $one . '\']=$' . $one . ";\n";
    }
}
?>



$stmt = $dbh->prepare($updateClause);

$stmt_r = $stmt->execute($bind_arr);
if($stmt_r){
return $stmt->rowCount();
}
else {

//echo 'error info:'.  var_export($stmt->errorInfo(),true);
return false;
}


}
catch ( PDOException $x ) {
//$errorMessage="database error: " . $x->getMessage();
throw $x;
}
<?=$this->custom_tailer_code;?>

}
