public function connectPDO(){
$engine='<?= $this->engine ?>';
$host='<?= $this->host ?>';
$port='<?= $this->port ?>';
$user='<?= $this->user ?>';
$dbname='<?if(!empty($this->dbname)):?><?=$this->dbname?><?endif?>';
$password='<?= $this->password ?>';




$dsn = "{$engine}:host={$host};port={$port};dbname={$dbname}";


$initPDO=array();
//$dsn.=';charset=UTF8';

//$initPDO[PDO::MYSQL_ATTR_INIT_COMMAND] = "SET NAMES utf8";

$dbh= new PDO($dsn, $user, $password,$initPDO);
return $dbh;
}

public function test($dbh){
        if($dbh===null){
            try {
                $dbh=  $this->connectPDO();
            } catch (Exception $exc) {
                error_log($exc->getMessage().".\n Trace:\n".  $exc->getTraceAsString());
                return false;
            }

            
        }
        
    }