
public function <?= $this->function_name ?>($dbh<?
foreach ($this->variables as $one) {
    echo ', $' . $one;
}
?>){
<?=$this->custom_header_code;?>

try {

$runQuery="DELETE FROM  ";
<?
foreach ($this->frome_tables as $one) {
    echo '$runQuery.="';

    echo '{' . $one['table_variable'] . '}';

    if (!empty($one['table_alias'])) {
        echo " as {$one['table_alias']}";
    }



    echo "\";\n";

    //update only support ont table;
    break;
}
?>
$bind_arr = array();

<?

if (!empty($this->where_claus)) {
    echo '$runQuery.=" ' . 'WHERE " ';
    foreach ($this->where_claus as $one) {
        echo "." . $one;
    }
    echo ";\n";
}
?>



<?
foreach ($this->variables as $one) {
    echo '$bind_arr[\':' . $one . '\']=$' . $one . ";\n";
}
?>




$stmt = $dbh->prepare($runQuery);

$stmt_r = $stmt->execute($bind_arr);
if($stmt_r){
return $stmt->rowCount();
}
else {

<? if (!empty($this->error_log)): ?>
        <?= $this->error_log ?>('db error info:' . var_export($stmt->errorInfo(), true)." query:".$runQuery);
    <? else: ?>
        //$errorMessage='db error info:' . var_export($stmt->errorInfo(), true)." query:".$runQuery;
    <? endif ?>
return false;
}


}
catch ( PDOException $x ) {
<? if (!empty($this->error_log)): ?>
    <?= $this->error_log ?>('db error info:' . $x->getMessage()." query:".$runQuery);
<? else: ?>
    //$errorMessage='db error info:' . $x->getMessage()." query:".$runQuery;
<? endif ?>
throw $x;
}
<?=$this->custom_tailer_code;?>

}
