<ul>

    <li>
        <a href="<?= $this->popUrl('html_builder/') ?>">
            Html Helper
        </a>
    </li>

    <li>

        <a href="<?= $this->popUrl('query_builder/') ?>">
            Mysql Helper
        </a>
    </li>
    <li>
        <a href="<?= $this->popUrl('index/phpinfo') ?>">
            Php Info
        </a>
    </li>

    <li>
        <a href="<?= $this->popUrl('code_duplicate/index') ?>">
            Code Duplicate
        </a>
    </li>



</ul>