<script type="text/javascript" >
    $(document).ready(function() {
        var options = [];
        options.push({
            uuid: 'adsadfasdf1',
            show_text: 'option1'
        });
        options.push({
            uuid: 'adsadfasdf2',
            show_text: 'option2'
        });
        options.push({
            uuid: 'adsadfasdf3',
            show_text: 'option3'
        });
        var cc = new QueryLogic("logics", null, options);

        cc.logic_view_rendering();

        $('#try_me').click(function(){
            $('#result').val(cc.toConditionStr());
        });
    });
</script>

<style>

</style>


<div id="logics">



</div>


<? include dirname(__FILE__) . '/../share/logic_edit.phtml'; ?>


<hr/>

<button id='try_me'>Try me</button>
<textarea id='result'></textarea>

