<script type="text/javascript" >
    $(document).ready(function() {
        var options = [];
        options.push({
            uuid: 'adsadfasdf1',
            column: {cname:'option1',talias:'tt'}
        });
        options.push({
            uuid: 'adsadfasdf2',
            column: {cname:'option2',talias:'tt'}
        });
        options.push({
            uuid: 'adsadfasdf3',
            column: {cname:'option3',talias:'dd'}
        });
        var cc = new QueryLogic("logics", null, options);

        cc.logic_view_rendering();

        $('#try_me').click(function(){
            $('#result').val(cc.toConditionStr());
        });
    });
</script>

<style>

</style>


<div id="logics">



</div>


<? include dirname(__FILE__) . '/../share/logic_edit.phtml'; ?>


<hr/>

<button id='try_me'>Try me</button>
<textarea id='result'></textarea>

